### PR TITLE
Generative Adversarial Networks

### PR DESCRIPTION
**Pull request by gabriben**
Here is my Submission on March 15 AoE.

I used imgur for images and https://tex-image-link-generator.herokuapp.com/ for math.

I wanted to keep the simple .md format at the cost of a less structured bibliography. I am happy to clean up the bibliography if this summary is considered useful. This includes adding links (most papers are on ArXiv).

I hope this is useful for you, it was useful for me because I was pushed into chairing a reading group on GANs on Friday -> two birds one stone ;)

### CODE REVIEW

**Comment by gabriben** [comment]
Hi, did I do something wrong in my submission? :(

**Comment by gabriben** [comment]
got it, I had forgotten to pull 1-2 new elements. I hope this solves the issues

**Comment by nicodjimenez** [comment]
Thank you for the submission! Merged with https://github.com/Mathpix/spectra-review-paper-competition/commit/e53389dd0ad13c87c5712e2a4d756317edd31bdf

**Comment by nicodjimenez** [comment]
Live at https://spectra.pub/ml/gans

**Pull request closed without merging**
