### PR TITLE
Visual Relationship Detection using Scene Graphs: A Survey (Submission)

### PR DESCRIPTION
**Pull request by aniket-agarwal1999**
Submission of a survey on scene graphs for this competition. Thanks :)

### CODE REVIEW

**Comment by th-anderson** [comment]
This review article has already been published:

https://arxiv.org/abs/2005.08045

**Comment by aniket-agarwal1999** [comment]
That is our "Arxiv" paper as well. This submission is a modified version of that and has some updations.

**Comment by aniket-agarwal1999** [comment]
@nicodjimenez can u please see the PR because I suppose the deadline is really close. Thanks :)

**Comment by nicodjimenez** [comment]
Merging, thanks for the submission!

Can you elaborate more on what you updated since that Arxiv submission?

**Comment by nicodjimenez** [comment]
Btw submission is live at:

https://spectra.pub/ml/visual-relationship-scene-graph

**Comment by aniket-agarwal1999** [comment]
Yeah sure, in this submission we have trimmed many of the unecessary stuff to cut the review a bit short and also removed description about some of the really old techniques as well which served really less to the purpose of giving a brief and wholesome gist of the subject. Apart from this, we have mainly updated in the Future Directions section a bit to refine it since we believed there were many other directions in this field that we did not know when finalizing the arxiv submission. Also updated the summarization of some of the methods for better understanding of the reader and same in the Applications section as well.

**Comment by aniket-agarwal1999** [comment]
Hi @nicodjimenez , our submission seems to have been removed. Is there a specific reason for it?

**Comment by nicodjimenez** [comment]
Ah you're right! Thanks for bringing this to our attention.  In any case, it's now fixed.  It was caused by one of the articles having broken frontmatter.

**Pull request merged**
